export enum CouponTypes {
  PERCENT_DISCOUNT_ON_ITEMS = "PERCENT_DISCOUNT_ON_ITEMS",
  FIXED_DISCOUNT_ON_TOTAL = "FIXED_DISCOUNT_ON_TOTAL",
  FREE_SHIPPING = "FREE_SHIPPING",
  PERCENT_POINTS_ON_ITEMS = "PERCENT_POINTS_ON_ITEMS",
  PERCENT_OF_TOTAL_IN_POINTS = "PERCENT_OF_TOTAL_IN_POINTS",
  PERCENT_OF_TOTAL_IN_DISCOUNT = "PERCENT_OF_TOTAL_IN_DISCOUNT",
  FIXED_POINTS_ON_TOTAL = "FIXED_POINTS_ON_TOTAL",
}
