export enum ProductPicturePurpose {
  STORE_LOBBY = "STORE_LOBBY",
  DETAILS = "DETAILS",
  CLINICAL_RESULTS_BEFORE = "CLINICAL_RESULTS_BEFORE",
  CLINICAL_RESULTS_AFTER = "CLINICAL_RESULTS_AFTER",
  TECHNICAL_SPEC = "TECHNICAL_SPEC",
}

export enum ProductPictureType {
  ICON = "ICON",
  SMALL = "SMALL",
  LARGE = "LARGE",
}

export enum ProductCategories {
  CONSUMABLES = "CONSUMABLES",
}
