export const palette = {
  primary_main: "#FF7F92" as const,
  primary_light: "#FAB3BD" as const,
  bg_dark: "#262323" as const,
  bg_pink: "#F6E2E1" as const,
  bg_auth_dark: "#212121" as const,
  accent_dark: "#DB6D7D" as const,
  hover_pink_light: "#F7D3D5" as const,
  grey: "#777676" as const,
  dark_grey: "#403B3B" as const,
  light_grey: "#D9D9D9" as const,
  black: "#000000" as const,
  white: "#ffffff" as const,
  dark_blue: "#051F3B" as const,
  red: "#F00" as const,
  pink_sceleton: "#F5DBD9" as const,
  // clinics app
  bg_clinics: "#F2F2F2" as const,
  blue: "#578FFF" as const,
  light_blue: "#b7ccf7" as const,
  grey_50: "#8A8A8A" as const,
};
